import PDFDocument from 'pdfkit'

export function generateCareerKeyPdf(attempt) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margins: { top: 50, bottom: 50, left: 44, right: 44 } })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    doc.fillColor('#0A2E1C').fontSize(18).font('Helvetica-Bold').text('SL Job Bank — Career Key Result')
    doc.fillColor('#555').fontSize(12).font('Helvetica').text('Sri Lanka Career Guidance Platform')
    doc.moveDown()

    const rows = [
      ['Student', attempt.user?.fullName || '-'],
      ['Completed', attempt.completedAt ? new Date(attempt.completedAt).toLocaleString() : '-'],
      ['Holland Code', attempt.hollandCode || '-'],
      ['Top Recommended Cluster', attempt.topCluster?.name || '-'],
    ]
    doc.font('Helvetica-Bold').fontSize(10)
    for (const [label, value] of rows) {
      doc.fillColor('#0A2E1C').text(label, { continued: true, width: 200 })
      doc.font('Helvetica').fillColor('#333').text('   ' + value)
      doc.font('Helvetica-Bold')
    }

    doc.moveDown()
    doc.fillColor('#0A2E1C').fontSize(13).font('Helvetica-Bold').text('Guidance')
    doc.moveDown(0.5)
    doc.fillColor('#333').fontSize(10).font('Helvetica').text(attempt.guidanceText || '', { align: 'left', lineGap: 3 })

    doc.moveDown()
    doc.fillColor('#999').fontSize(8).font('Helvetica-Oblique').text(
      'This result reflects interests, not fixed ability or destiny. Use it as a starting point for exploration ' +
      'and discuss it with a school counselor. Generated by SL Job Bank.'
    )

    doc.end()
  })
}
